package edu.manipal.icas.simple.models;

public enum ApplicationStatus {
	INITIATED,
	FORM_FILLED,
	SLOT_BOOKED,
	PAYMENT_COMPLETE,
	CAPTURING_BIOMETRICS,
	UNDER_VERIFICATION,
	UNDER_REVIEW,
	PENDING_ADDRESS_VERIFICATION,
	ADDRESS_VERIFICATION_CLEAR,
	ADDRESS_VERIFICATION_ADVERSE,
	ADDRESS_VERIFICATION_INCOMPLETE,
	COMPLETED_AND_SUCCESSFUL,
	REJECTED
}
