# This is a basic workflow to help you get started with Actions

name: Java Build

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build sources
        working-directory: ./SIMPLE
        run: |
              mkdir build
              javac -cp "src:lib/*" src/edu/manipal/icas/simple/Main.java -d build