# This is a basic workflow to help you get started with Actions

name: Java Build

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: 
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.0

      - name: Build sources
        working-directory: ./SIMPLE
        run: |
              mkdir build
              javac -cp src src/edu/manipal/icas/Main.java -d build
