# This is a basic workflow to help you get started with Actions

name: Java JUnit Test

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  push:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build sources
        working-directory: ./SIMPLE
        run: |
              mkdir build
              javac -d build -cp "src:lib/*" src/edu/manipal/icas/simple/tests/TestSuite.java

      - name: Copy resources to /build
        working-directory: ./SIMPLE
        run: |
              cp -a src/edu/manipal/icas/simple/resources/. build/edu/manipal/icas/simple/resources

      - name: Run Tests
        working-directory: ./SIMPLE
        run: java -cp "build:lib/*" org.junit.runner.JUnitCore edu.manipal.icas.simple.tests.TestSuite